config/routes.rb
Rails.application.routes.draw do
  get "books/search", to: "books#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # 主キーを記述
  self.primary_key = "isbn"
  has_many :reviews, dependent: :destroy
end

app/models/concerns/rakuten_books_search.rb
require 'active_support'

module RakutenBooksSearch
  extend ActiveSupport::Concern

  # 共通処理を記述
  def componentization
    @books = []
    @title = params[:title]

    if @title.present?
      # resultsに楽天APIから取得したjsonデータを格納
      # 書籍のタイトルを検索して、一致するデータを格納するように設定
      results = RakutenWebService::Books::Book.search({title: @title})
        
      # @booksに格納
      results.each do |result|
          book = Book.new(read(result))
          @books << book
      end
    end
    
    book_save
  end

  def read(result)
    title = result["title"]
    author = result["author"]
    url = result["itemUrl"]
    isbn = result["isbn"]
    image_url = result["mediumImageUrl"].gsub('?_ex=120x120', '')
    book_genre_id = result["booksGenreId"]
    item_caption = result["itemCaption"]
    {
      title: title,
      author: author,
      url: url,
      isbn: isbn,
      image_url: image_url
    }
  end

  def book_save
    # すでに保存済の本はunlessで除外
    # トランザクション内でrescueを使用するとロールバックが行われないため以下のようにトランザクションの外側で例外をキャッチする
    Book.transaction do
      @books.each do |book|
        unless Book.all.include?(book)
          book.save!
         end
      end
    end
    # 1
    rescue ActiveRecord::Rollback, "ロールバックする"
    Rails.logger.debug e.message
  end
end

# 1
# 例外処理がメソッド定義全体に対して行われる場合には begin と end を省略できる


# gsubメソッドは特定の文字を別の文字へ置換するだけでなく、正規表現を用いて該当する箇所を置換したり削除できるメソッド
# 正規表現を使わない場合
# 文字列.gsub(置換したい文字列, 置換後の文字列)

# 正規表現を使う場合
# 文字列.gsub(/正規表現/, 正規表現に該当した箇所を置換した後の文字列)

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  # bookモデルのisbnカラムを主キーとして設定
  belongs_to :book, primary_key: "isbn"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # ファイル名とモジュール名を揃えないと読み込めない
  include RakutenBooksSearch

  def search
    # 共通化した処理
    componentization
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/search.html.erb
<%= form_tag(books_search_path, method: :get) do %>
  <%= text_field_tag :title, @title %>
  <%= button_tag type: "submit" %>
<% end %>

<% if @books %>
  <% @books.each do |book| %>
    <%= image_tag book.image_url %>
    <%= book.title %>
    <%= book.author %>
    <%#= book.item_caption %>    
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UseRakutenApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>